### PR TITLE
Add Chip component

### PR DESCRIPTION
**Pull request by isomoar**
Basic implementation of Chip with "selected" attribute, leading and trailing icons.

### CODE REVIEW

**Comment by aforemny** [comment]
Hi @isomoar, welcome and thank you very much for taking on this issue! I will review and merge this as soon as I can. :-)

**Comment by aforemny** [comment]
Hi @isomoar, I finally managed to look at your PR! Thank you again for this contribution. I am very happy with the API that you implemented for the Chip and ChipSet components!

I merged this in 802e01dfa6ca737fba0005907719b0d4ccf2cbe0, 43581f98d6a011348d379d17b0653f078d075279 with some suggested improvements in 2d2f5cd7328b4da66019a13382864a3ce8b67bfa and deec41ca39b31b6b03af8ec1c60a9ab49ff2538f.

The second suggestion aligns our demo with the [upstream demo](https://material-components.github.io/material-components-web-catalog/#/component/chips) more, the first sets a tabindex of zero automatically and exposes the Chip documentation.

Comparing the two demos I see that some functionality is missing in ours:
- our filter chips do not draw the check mark icon if they are selected
- our chips do not respond to keyboard events (Enter should select them)

Is that something that you would like to improve upon? (It is fine if you don't feel like doing that.)

**Comment by isomoar** [comment]
Hi @aforemny, thank you for taking a look at my PR! Yes, I would like to make these improvements in the nearest time.

**Comment by aforemny** [comment]
Hi. Sorry for the lack of progress. I am a bit swamped right now, but I have started to work on merging this and will finish it as soon as I have the time. :)

**Comment by aforemny** [comment]
Hi @isomoar, I finally merged this in 80e3d43a209d5cae9fb0f6cd47e3c01a93b5b3df and e69312aac1af638de2c8ceb559ed56d37721b138 with only minor modifications in 96771eca45e457df069036cb8c54614956227805. Thank you very much for this contribution, and sorry for the delay!

**Pull request closed without merging**
