### PR TITLE
Update to mdc 0.42.1

### PR DESCRIPTION
**Pull request by berenddeboer**
Here the mother of all pull requests. Apologies it is a lot, there were significant changes in 0.38.

I have made a CHANGELOG.md so users know what to expect in the upgrade.

I think it is in a state where it is better than what we have in the 0.37, but there are some remaining issues:
* Dismissable drawer does not work. I believe this is possible Elm bug. See Demo/DismissibleDrawer.elm: the model.drawerOpen gets set to True, then flashes back to False for no apparent reason (no messages that I can see).
* Modal drawer: should support Esc key. Couldn't get that to compile. In theory this should be easy: on Esc, send config.onClose. See comments in source.
* Dialog should support Esc + Enter key. Couldn't get that to work for the same reason.
* TabBar: on click the element should receive focus. See my comment while handling new msg SetActiveTab. That's probably the point where you want to focus the clicked tab. But couldn't get my attempts to compile.
* TabBar: scrolling does not work. I think once focus works, I would know what Elm code to write to make the focus work.
* TabBar: have hard-coded the calculation of the horizontal scrollbar height to 10px. In mdc that's calculated dynamically. Probably easiest to put that code in elm-mdc.js.
* TabBar: ripples are not the same. It seems in the more recent version of mdc they have a separate ripple div inside the element, and the mdc-ripple-upgraded is set on that class, but the current ripple implementation only handles ripples on the container class. This may need work.

### CODE REVIEW

**Comment by berenddeboer** [comment]
On closing the dialog and drawer: looking at how the menu does it, I'm a bit perplexed. It seems on Escape it closes the menu without updating the global model by just updating the internal model open state.

Wouldn't this create a discrepancy between the global state and the local internal state? I thought one of Elm's key ideas was to avoid this.

What I would have expected to see is what I tried to do: sending a request to close the menu back to the main update.

**Comment by aforemny** [comment]
Hi @berenddeboer,

thank you for this massive contribution. It seems to be very high-quality overall, too. :-)

I have just now looked through the demo and I have found the following regressions?. If you could help me fix them before I merge this, I would greatly appreciate it!

- [ ] Filter chips with leading icons do not replace the leading icon with the check mark, but rather draw the check mark in addition to the leading icon
- [ ] Icon Button hero is off center
- [ ] Icon Button Font Awesome example does not show
- [ ] Layout Grid demo does not seem quite right (the two bottom examples)
- [ ] Menu auto positioning does not seem to work (if you change the button position to bottom, it should open to the top rather than to the bottom)
- [ ] Snackbar demo, dismissing a snack by clicking the hide button does not work
- [ ] Text field demo, hero, filled and outlined text fields share IDs (the two rightmost text field)

I am planning to look at your original questions next.

**Comment by aforemny** [comment]
Hi @berenddeboer, I will be pushing commits to the update-to-0.42.1 branch. There is a formatting commit that I would like you to rebase against, so that we minimize formatting changes in our PRs.

**Comment by berenddeboer** [comment]
>>>>> "Alexander" == Alexander Foremny <notifications@github.com> writes:

    Alexander> I have just now looked through the demo and I have
    Alexander> found the following regressions

Hi Alexander,

Was away, so just came back to this. I've rebased on master, will work
on these issues asap.


--
All the best,

Berend de Boer

**Comment by berenddeboer** [comment]
Have now upgraded to 0.43.0 as I had to work on the snackbar. Snackbar upgraded, dismiss on action now working.

**Comment by berenddeboer** [comment]
OK, that's all.

One oddity to add: because of the focus trap the "mdc-dialog-scroll-lock" element is added. This causes the vertical scrollbar to disappear, which makes the screen jump (it gets 10 pixels wider or so). Very odd, because the Google demo adds this class too for the dialog demo, but the scrollbar does not disappear, and therefore they don't have this jump.

Google does not add "mdc-dialog-scroll-lock" for the menu demo, and I believe we should not do that either. You still want to be able to scroll the screen. So I removed focustrap here. Had a quick look, but looks like Google doesn't use focus trap either (could be wrong). This means keyboard currently does not work (only the Esc key worked before).

**Comment by aforemny** [comment]
Hi @berenddeboer, thank you very much for addressing the regression issues that I've mentioned!

I have finally found the time to look at your original questions, and I think I've addressed them with the recent commits to my update-to-0.42.1 branch. I included some information in the commit messages. Could you please cherry-pick my commits into your branch so that this PR gets updated?

Anything I did not address, or anything else that we should look at? Or is this PR good to go? If so, I will work on merging it.

**Comment by aforemny** [comment]
Hi @berenddeboer, I updated started to update the demo files to familiarize myself with the changes. I still have to get to updating the following demos:

-[ ] Snackbar demo: Check Snackbar demo
-[ ] Theme demo: Check Theme demo
-[ ] TopAppBar demo: Check TopAppBar demo
-[ ] Typography demo: Check Typography demo

I have found the following unordered list of issues that we do not need to address to get this merged. But if you could help out, I would appreciate it:

-[ ] Material: Replace IconToggle with IconButton
-[ ] Material: Add extended FAB
-[ ] Material: Lists should ripple by default
-[ ] Material: Enhanced Select
-[ ] Material: Select `nativeControl` property (see Demo.Selects, TODO)
-[ ] Demo: Check for unused imports
-[ ] Demo: Add Drawer
-[ ] Demo: Remove page.hero (deprecated by Hero.view)
-[ ] Demo: Remove page.demos (deprecated by Page.demos)
-[ ] Demo: Refactor Resources
-[ ] Card demo: Use IconButton
-[ ] Card demo: Use correct image
-[ ] Chip demo: Checkmark is white instead of black
-[ ] Fab demo: Add extended FAB examples
-[ ] Icon Toggle demo: Use Icon Button
-[ ] LayoutGrid demo: Rethink `LayoutGrid.inner` (Cell Alignment demo)
-[ ] List demo: List items should ripple
-[ ] Ripple demo: Unbounded ripple glitch
-[ ] Ripple demo: What's up with class `mdc-ripple-surface`?
-[ ] Select demo: Enhanced selects
-[ ] Select demo: shapedOutlinedSelect (TODO)
-[ ] TabBar demo: Key controls (Left- and RightArrow keys)
-[ ] TabBar demo: Scrolling (click on TAB TWO, it should not scroll)
-[ ] TextFields demo: Shaped Outlined TextFields
-[ ] TextFields demo: Multiline text fields shouldn't specify `TextField.outlined`

I apologize for removing two features from the demo that you seem to have implemented, because they are not contained in the upstream demo (TabBar and TextFields demos). If you would like to include them, let me know and I will add them back! I could not make sense of the TabBar demo, so if you could explain what you were trying to show there, please do! The overlaid star icons seemed to be broken to me (Firefox browser).

**Comment by berenddeboer** [comment]
> Anything I did not address, or anything else that we should look at? Or is this PR good to go? 

This PR is good to go I think, but no doubt issues will popup. When working on this I found/fixed bugs/missing stuff from previous releases. But I think the state so far is better then the current state.

>If so, I will work on merging it.

Thanks!

**Comment by berenddeboer** [comment]
> I included some information in the commit messages.

Really? I started basically from your latest master, I can't see your last 4 commits added anything here.

Main issue for me is the focus one: how to get dialog keyboard interaction going, same for menu.

**Comment by berenddeboer** [comment]
OK, working on the TabBar scrolling, making some progress.

**Comment by berenddeboer** [comment]
Scrolling improved. I think I might be able to animate this too, but I'm having trouble with Json decoding. In decodeGeometry I need to find the .mdc-tab__content class, which I attempted crudely, but the dimensions variable is a `Decoder {}` so I can't extract the values that way.

Perhaps I need to do something more complicated? But perhaps there is easy access to the child node, so I'm hoping this is easy for @aforemny.

**Comment by wscherphof** [comment]
What is needed to get this going again? Looks like full of niceties!

**Comment by berenddeboer** [comment]
Maybe some work on the demo? I'm going to have time to work on the demo soon, but don't think we need them to be supernice to get this merged. So just waiting for Alexander I think. Seems to be pretty busy, hopefully for him with Elm work :-)

**Comment by wscherphof** [comment]
😃🙌👏❤

**Pull request merged**
