### PR TITLE
Update to v0.39.1

### PR DESCRIPTION
**Pull request by berenddeboer**
Updates:
1. Drawer drastically changed.
2. Textfield.box is now the default, option removed.
3. Textfield upgraded class gone, now default.

That's all changes as far as I could see.

What I couldn't fix for the Drawer:
1. don't see proof mdc-drawer--closing is every applied.
2. is the opening/closing animation working?
3. The mdc version allows closing the drawer by pressing Esc. I tried to support that, but it fails, drawer closes and immediately gets reopened. Probably I should return a msg of config.onClose, but doing that gave me type errors.
4. The mdc drawer also allows cursor navigation: up and down keys. I think that might be very hard to do in Elm. I suppose we can return the up/down commands, and let the client program maintain some index. I'm happy to have a look at this once 3 works.

### CODE REVIEW

**Comment by berenddeboer** [comment]
Rebased.

**Comment by aforemny** [comment]
Hi @berenddeboer, apologies for the long delay. Unfortunately, I will not be able to update to 0.39.* any time soon. I am currently looking into updating 0.38.2, and even that seems like a fair amount of work.

Lets discuss options to update to 0.39.* once this is done. I will close this until then. Sorry!

**Comment by aforemny** [comment]
Or actually, let's keep it open since you have done a fair amount of work here already.

**Comment by berenddeboer** [comment]
What's the problem? I did most of the work I believe. Do I need to rebase against master?

I think for elm-mdc to be most successful it should follow mdc very closely and reasonably timely.

**Comment by aforemny** [comment]
Hi @berenddeboer, looking at the demo I have found issues with the following components:

- List (two line lists)
- Ripple
- Menu
- Switch
- Tabs

I am planning to look at Tabs and Drawers next, but I would appreciate any help with the others if you would be up for that. :-)

**Comment by berenddeboer** [comment]
Yes, definitely up for maintaining this! I'll have a look at lists, that might be the easiest.

**Comment by aforemny** [comment]
@berenddeboer If you are having trouble rebasing this against master (which is elm 19 now), feel free to rebase against elm-18 branch.

**Comment by berenddeboer** [comment]
No more work will be done on this branch, all work has gone in the [Elm 0.19 v0.42 branch](https://github.com/berenddeboer/elm-mdc/tree/update-to-v0.42.1).

**Pull request closed without merging**
