### PR TITLE
Drawer extension to support MDC Web v0.35.1

### PR DESCRIPTION
**Pull request by berenddeboer**
OK a much bigger update, as you know I don't know elm, so hopefully this is acceptable! This makes creating structures to support 0.35.1 easier. Have updated the demo (this patch includes my other pull request change to the iframe, else I couldn't easily test).

Patch does not break existing code (but that code looks broken on the screen), it's just an extension.

### CODE REVIEW

**Comment by aforemny** [comment]
It seems I am mistaken and the work-around proposed at the bottom does not work. I think I know what to do now, no need to answer my questions from before.

**Comment by berenddeboer** [comment]
Great thanks. as you already have seen you need "<nav>" now for the 0.35.1 update, not "<ul>". Basically what this does it creating the [output mentioned in the docs](https://material.io/develop/web/components/drawers/).

Motivation for listItem as per [a discussion I had in discourse](https://discourse.elm-lang.org/t/addclass-html-m-html-m/1256), I wanted to iterate over the items and add the class, but that's not possible I found out, so I needed a helper function.

**Comment by aforemny** [comment]
Hi @berenddeboer, I ended up implementing this in a different way. Could you please test if [this change](https://github.com/aforemny/elm-mdc/commit/8263229ffc803b0d10d364882188b25b6ae0f778#diff-e2033529838ccc93f7a2aed90c2f3e30) works for you? I uploaded the demo here: [demo](https://aforemny.github.io/elm-mdc/#temporary-drawer).

**Comment by berenddeboer** [comment]
At least the drawer looks fine! So that is solved.

But I have two problems with the generated output:
* It doesn't look like [the example code](https://material.io/develop/web/components/drawers/).
* It looks very odd: we have a <ul> with no <li> (except the separator), just <a>'s.

This will be just very confusing, and potentially generate many questions from users in the future. I.e. when there is a problem, the first thing you do is look at the output, compare with the example, and think the issue is with elm-mdc, and try mimicking the example anyway.

So I would still get rid of the list, i.e. prefer something like my solution. But the visual issues have been solved, so however you decide to do this, it'll work for me.

**Comment by berenddeboer** [comment]
One more thought: at minimum I would get the <nav> instead of <div> that might be important for screen readers for visually impaired users, or for SEO.

**Comment by aforemny** [comment]
Hi @berenddeboer, I agree with your concerns. I decided to expose `Lists.nav` analog to `Lists.ul` (see  2d82a1f8c1d94e6352184be1c30cd4349c899a79). Now we can write either

`Lists.ul [] [ Lists.li [] [], … ]` or `Lists.nav [] [ Lists.a [] [], … ]`

Does that meet your use-case?

**Comment by berenddeboer** [comment]
Totally happy with this!

**Pull request closed without merging**
