### PR TITLE
Implementation of TopAppBar

### PR DESCRIPTION
**Pull request by berenddeboer**
My most massive pull request! Upgrade to v0.35.1. Added TopAppBar support. And I realised I had to reimplement the javascript in Elm, bold move to do it that way :-) I hope I copied that all correctly.

A couple of issues:
* Toggle RTL button doesn't work (neither does it in toolbar demo). The biggest issue here is not having a command to send. I'm unsure how to add custom commands in a demo page, would be quite useful, because then I could make the menu demo work too.
* Elm compilation has become an issue: takes over 16GB to compile.
* You have to supply hasItemAction class for the short versions, the JavaScript version adds that automatically, which certainly would be nicer. I suppose I could simply count the items in the second section, not sure I can do that.
* The javascript version does not register a scrollhandler when not needed, the Elm version always does that (just like the toolbar version).
* I think with the upgrade to v0.35.1 it's good enough to be listed as library on the [main Material Components Web page](https://github.com/material-components/material-components-web).

### CODE REVIEW

**Comment by berenddeboer** [comment]
Upgrade to v0.35.1 broke floating labels, class change. Fixed that in another commit.

However, this does not work well. If you click on the label, the input does not get the focus. I'm not sure how to fix this. Basically the input control should have an id, and the label can then have a "for" attribute, and it'll work well. That's my preferred approach. I need ids on almost any element anyway.

I already pass in an id via `Textfield.nativeControl [ Options.attribute (id "email") ]`. However, was unable to extract this due to my lack of Elm skills.

But would be much better if I could simply pass in `Options.attribute (id "email")` without using nativeControl. An id on the wrapper makes no sense (I can't come up with any use case) anyway, so that id can be used for the input,and for the label elements.


Or introduce a Textfield.id property. That's something I could add as I think I understand that concept


The other approach would be to handle onClick on the label, then focus the input. But why do this work when the browser can do this for you?

**Comment by aforemny** [comment]
Hi @berenddeboer, thank you for this massive contribution! I will review and merge this soon as I can! :+1:

**Comment by berenddeboer** [comment]
Found a much better solution: instead of using a div wrapper, use a label wrapper as per (Avoid Dynamic ID generation)[https://material.io/develop/web/components/input-controls/floating-label/].

I noticed outlines are not working any more, just fixing them too, then it seems this is actually ready for commit as I don't have any outstanding issues.

**Comment by berenddeboer** [comment]
On Toggle RTL: when looking at the Textfields demo I saw how to integrate that. I can do Elm copy/paste programming, so that now works too.

**Comment by aforemny** [comment]
Hi @berenddeboer, I pushed this to master as commits ca797039488b8e1b9ac4189bb9530a99858b6bb6 – d3bd9a0c8c3faf23bab8c91bfb666cb362205dc2.

Thank you very much for the effort you are putting in to update the components to v0.35 and for the initial implementation of the TopAppBar. It worked perfectly when I first tested it!

I have since then compared it to the implementation in
[./mdc-top-app-bar/standard/foundation.js](https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/standard/foundation.js) and added some missing JS bits that are mostly concerned with the resize events.

Feel free to contact me if you have any questions or feedback!

**Comment by aforemny** [comment]
> Elm compilation has become an issue: takes over 16GB to compile.

This has to do with long case expressions in `Demo.Url.toString/fromString`, I fixed it by splitting the cases up further.

**Pull request closed without merging**
